---
- hosts: servers

  tasks:

  - name: docker hello world
    shell: docker run hello-world
    register: result

  - name: result
    debug: msg="Working"
    when: result.stdout | search("This message shows that your installation appears to be working correctly.")


